name: xwidget
description: A package for building dynamic UIs in Flutter using an expressive, XML based markup language.
version: 0.1.1
repository: https://github.com/appfluent/xwidget
issue_tracker: https://github.com/appfluent/xwidget/issues

topics:
  - dynamic
  - layout
  - ui
  - widgets
  - xml

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.19.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.6.1
  xml: ^6.6.1
  xwidget_el: ^0.2.0

dev_dependencies:
  args: ^2.7.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ">=1.25.15 <1.28.0"

# For information on the generic Dart part of this file, see the
# The following section is specific to Flutter packages.
flutter:
